### PR TITLE
Fix up identifier defaulting.

### LINKED ISSUE #735: [Improvement] Set default Identifiers based on the default configuration
Extended from https://github.com/cakephp/authentication/issues/733 , expanded into it's own issue as the previous is addressed. 

Identifiers are now to be set per Authenticator. 
But some Authenticators ask for an Identifier when they may not need one. For example, Form shouldn't need one if it's [username, password] as those are the default fields https://github.com/cakephp/authentication/blob/3.x/src/Authenticator/FormAuthenticator.php#L44 , so IMO the default Identifier should be `Authentication.Password`.

This feels like it should be enough
```php
    public function getAuthenticationService(ServerRequestInterface $request): AuthenticationServiceInterface
    {
        $service = new AuthenticationService([
            'unauthenticatedRedirect' => [
                'prefix' => false,
                'plugin' => null,
                'controller' => 'Users',
                'action' => 'login',
            ],
            'queryParam' => 'redirect',
        ]);

        // Load the authenticators. Session should be first.
        $service->loadAuthenticator('Authentication.Session');
        $service->loadAuthenticator('Authentication.Form');

        return $service;
    }
```

Rather than needing to do this:
```php
    public function getAuthenticationService(ServerRequestInterface $request): AuthenticationServiceInterface
    {
        $service = new AuthenticationService([
            'unauthenticatedRedirect' => [
                'prefix' => false,
                'plugin' => null,
                'controller' => 'Users',
                'action' => 'login',
            ],
            'queryParam' => 'redirect',
        ]);

        // Load the authenticators. Session should be first.
        $service->loadAuthenticator('Authentication.Session');
        $service->loadAuthenticator('Authentication.Form', [
            'identifier' => 'Authentication.Password',
        ]);

        return $service;
    }
```

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/authentication/issues/735

  This makes the authentication setup much simpler. Developers can now use:
```php
  $service->loadAuthenticator('Authentication.Form');
  $service->loadAuthenticator('Authentication.HttpBasic');
  $service->loadAuthenticator('Authentication.Cookie');
  $service->loadAuthenticator('Authentication.Token');
  $service->loadAuthenticator('Authentication.Jwt');
```
  All without needing to explicitly configure identifiers, as sensible defaults are provided.

### CODE REVIEW

File: src/Authenticator/FormAuthenticator.php [hunk 1]
```diff
@@ -47,6 +49,22 @@ class FormAuthenticator extends AbstractAuthenticator
...
+     * Constructor
+     *
+     * @param \Authentication\Identifier\IdentifierInterface $identifier Identifier or identifiers collection.
+     * @param array<string, mixed> $config Configuration settings.
+     */
+    public function __construct(IdentifierInterface $identifier, array $config = [])
+    {
+        // If no identifier is configured, set up a default Password identifier
+        if ($identifier instanceof IdentifierCollection && $identifier->isEmpty()) {
+            $identifier = new IdentifierCollection(['Authentication.Password']);
```
Comment (ADmad) [inline src/Authenticator/FormAuthenticator.php]: If we are setting a default identifier then I would expect it to be auto configured to as per the authenticator config. For e.g. if the `fields.username` config is set to `email` for the authenticator, then the same should be passed to the identifier too. Currently we have this redundancy where we have to configure it for both the authenticator and the identifier.

Comment (dereuromark) [reply src/Authenticator/FormAuthenticator.php]: I added a commit, is that what you had in mind?

File: src/Authenticator/JwtAuthenticator.php [hunk 2]
```diff
@@ -56,7 +57,13 @@ class JwtAuthenticator extends TokenAuthenticator
...
     public function __construct(IdentifierInterface $identifier, array $config = [])
     {
-        parent::__construct($identifier, $config);
+        // Override parent's default - JWT should use JwtSubject identifier
+        if ($identifier instanceof IdentifierCollection && $identifier->isEmpty()) {
+            $identifier = new IdentifierCollection(['Authentication.JwtSubject']);
+        }
+
+        // Call TokenAuthenticator's constructor but skip its default
+        AbstractAuthenticator::__construct($identifier, $config);
```
Comment (markstory) [inline src/Authenticator/JwtAuthenticator.php:66]: Should this be `parent::__construct()`?

Comment (dereuromark) [reply src/Authenticator/JwtAuthenticator.php:66]: Then it would trigger the Token ones default I guess.

Comment (markstory) [reply src/Authenticator/JwtAuthenticator.php:66]: Hrm. If we need different behavior perhaps we should undo the inheritance and duplicate some code. We can do that separately too.

**Review by markstory — APPROVED** [review]
Looks good to me.

**Comment by dereuromark** [comment]
ping @ADmad

**Review by ADmad — APPROVED** [review]
